package com.minha_sala_de_aula.Professor;

import com.minha_sala_de_aula.GUI.FormValidacao;
import com.minha_sala_de_aula.GUI.GUI_Principal;
import com.minha_sala_de_aula.GUI.PanelProfessor;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

public class FormFormacao extends javax.swing.JFrame implements FormValidacao {
    private Formacao formEdit;
    
    public FormFormacao() {
        initComponents();
        formEdit = null;
    }
    
    public FormFormacao(Formacao formEdit){
        initComponents();
        this.formEdit = formEdit;
        
        tfInstituicao.setText(formEdit.getInstituicao());
        tfCurso.setText(formEdit.getCurso());
        tfAnoInicio.setText(formEdit.getAnoInicio());
        tfAnoTermino.setText(formEdit.getAnoFinal());
        cbxEscolaridade.setSelectedItem(formEdit.getEscolaridade());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDegradeAzul1 = new com.minha_sala_de_aula.Fabrica.PanelDegradeAzul();
        panelFolhas1 = new com.minha_sala_de_aula.Fabrica.PanelFolhas();
        pnFormacao = new javax.swing.JPanel();
        lbFormacao = new javax.swing.JLabel();
        lbInstituicao = new javax.swing.JLabel();
        lbCurso = new javax.swing.JLabel();
        lbEscolaridade = new javax.swing.JLabel();
        lbAnoInicio = new javax.swing.JLabel();
        lbAnoTermino = new javax.swing.JLabel();
        cbxEscolaridade = new javax.swing.JComboBox<>();
        tfInstituicao = new javax.swing.JTextField();
        tfCurso = new javax.swing.JTextField();
        tfAnoInicio = new javax.swing.JTextField();
        tfAnoTermino = new javax.swing.JTextField();
        btCancelar = new javax.swing.JButton();
        brConfirmar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnFormacao.setOpaque(false);

        lbFormacao.setFont(new java.awt.Font("Noto Sans", 1, 24)); // NOI18N
        lbFormacao.setForeground(new java.awt.Color(0, 0, 0));
        lbFormacao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbFormacao.setText("Formação");

        lbInstituicao.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        lbInstituicao.setForeground(new java.awt.Color(0, 0, 0));
        lbInstituicao.setText("Instituição");

        lbCurso.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        lbCurso.setForeground(new java.awt.Color(0, 0, 0));
        lbCurso.setText("Curso");

        lbEscolaridade.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        lbEscolaridade.setForeground(new java.awt.Color(0, 0, 0));
        lbEscolaridade.setText("Escolaridade");

        lbAnoInicio.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        lbAnoInicio.setForeground(new java.awt.Color(0, 0, 0));
        lbAnoInicio.setText("Ano de Início");
        lbAnoInicio.setToolTipText("Ano de Início");

        lbAnoTermino.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        lbAnoTermino.setForeground(new java.awt.Color(0, 0, 0));
        lbAnoTermino.setText("Ano de Término");

        cbxEscolaridade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Curso Livre", "Técnico", "Bacharelado", "Licenciatura", "Mestrado", "Mestrado Profissional", "Doutorado", "Pós Doutorado" }));
        cbxEscolaridade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxEscolaridadeActionPerformed(evt);
            }
        });

        tfInstituicao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 153)));
        tfInstituicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfInstituicaoActionPerformed(evt);
            }
        });

        tfCurso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 153)));
        tfCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCursoActionPerformed(evt);
            }
        });

        tfAnoInicio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 153)));

        tfAnoTermino.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 153)));
        tfAnoTermino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAnoTerminoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnFormacaoLayout = new javax.swing.GroupLayout(pnFormacao);
        pnFormacao.setLayout(pnFormacaoLayout);
        pnFormacaoLayout.setHorizontalGroup(
            pnFormacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnFormacaoLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pnFormacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnFormacaoLayout.createSequentialGroup()
                        .addComponent(lbInstituicao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfInstituicao))
                    .addGroup(pnFormacaoLayout.createSequentialGroup()
                        .addComponent(lbAnoInicio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfAnoInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbAnoTermino)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfAnoTermino, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnFormacaoLayout.createSequentialGroup()
                        .addComponent(lbCurso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbEscolaridade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxEscolaridade, 0, 194, Short.MAX_VALUE)))
                .addGap(25, 25, 25))
            .addComponent(lbFormacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnFormacaoLayout.setVerticalGroup(
            pnFormacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnFormacaoLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(lbFormacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnFormacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbInstituicao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfInstituicao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnFormacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfCurso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnFormacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbEscolaridade)
                        .addComponent(cbxEscolaridade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbCurso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnFormacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfAnoInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnFormacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tfAnoTermino, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(pnFormacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbAnoInicio)
                            .addComponent(lbAnoTermino))))
                .addGap(18, 18, 18))
        );

        btCancelar.setIcon(new javax.swing.ImageIcon("/run/media/tomazaudio/ed644f64-c403-47df-b53b-4b1c2e37f556/SENAC/Projetos Java/Minha_Sala_de_Aula/src/main/resources/icon/Botao_Cancelar.png")); // NOI18N
        btCancelar.setBorderPainted(false);
        btCancelar.setContentAreaFilled(false);
        btCancelar.setPressedIcon(new javax.swing.ImageIcon("/run/media/tomazaudio/ed644f64-c403-47df-b53b-4b1c2e37f556/SENAC/Projetos Java/Minha_Sala_de_Aula/src/main/resources/icon/Botao_Cancelar_Pressed.png")); // NOI18N
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        brConfirmar.setIcon(new javax.swing.ImageIcon("/run/media/tomazaudio/ed644f64-c403-47df-b53b-4b1c2e37f556/SENAC/Projetos Java/Minha_Sala_de_Aula/src/main/resources/icon/Botao_Confirmar.png")); // NOI18N
        brConfirmar.setToolTipText("");
        brConfirmar.setBorderPainted(false);
        brConfirmar.setContentAreaFilled(false);
        brConfirmar.setPressedIcon(new javax.swing.ImageIcon("/run/media/tomazaudio/ed644f64-c403-47df-b53b-4b1c2e37f556/SENAC/Projetos Java/Minha_Sala_de_Aula/src/main/resources/icon/Botao_Confirmar_Pressed.png")); // NOI18N
        brConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brConfirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelFolhas1Layout = new javax.swing.GroupLayout(panelFolhas1);
        panelFolhas1.setLayout(panelFolhas1Layout);
        panelFolhas1Layout.setHorizontalGroup(
            panelFolhas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFolhas1Layout.createSequentialGroup()
                .addComponent(btCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(brConfirmar)
                .addGap(25, 25, 25))
            .addComponent(pnFormacao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelFolhas1Layout.setVerticalGroup(
            panelFolhas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFolhas1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(pnFormacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFolhas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btCancelar)
                    .addComponent(brConfirmar))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelDegradeAzul1Layout = new javax.swing.GroupLayout(panelDegradeAzul1);
        panelDegradeAzul1.setLayout(panelDegradeAzul1Layout);
        panelDegradeAzul1Layout.setHorizontalGroup(
            panelDegradeAzul1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDegradeAzul1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelFolhas1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelDegradeAzul1Layout.setVerticalGroup(
            panelDegradeAzul1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDegradeAzul1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelFolhas1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelDegradeAzul1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelDegradeAzul1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cbxEscolaridadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxEscolaridadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxEscolaridadeActionPerformed

    private void brConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brConfirmarActionPerformed
        mudarCor();
        if (camposVazios()){
            JOptionPane.showMessageDialog(null, """
                                                    O cadastro de sua formação está quase completo.
                                                
                                                Verifique se há algum campo vazio e de que a Escolridade
                                                foi escolhida corretamente.
                                                """);
        }else{
            if(validarCampos()){
                mudarCor();
                JOptionPane.showMessageDialog(null, """
                                                        O cadastro de sua formação está quase completo.

                                                    Verifique se os campos estão preenchidos corretamente.
                                                    
                                                            - Instituição/Curso - Apenas letras.
                                                            - Início/Término - 4 números.
                                                    """);
            }else{
                FormacaoJPA formJPA = new FormacaoJPA();
                
                if(formEdit == null){//Cadastrar uma nova formação
                    
                    Formacao formNova = new Formacao();

                    formNova.setInstituicao(tfInstituicao.getText());
                    formNova.setCurso(tfCurso.getText());
                    formNova.setEscolaridade(String.valueOf(cbxEscolaridade.getSelectedItem()));
                    formNova.setAnoInicio(tfAnoInicio.getText());
                    formNova.setAnoFinal(tfAnoTermino.getText());
                    formNova.setProfessor(GUI_Principal.getProfessor());

                    formJPA.cadastrar(formNova);
                    
                }else{//Editar uma formação selecionada
                    
                    formEdit.setInstituicao(tfInstituicao.getText());
                    formEdit.setCurso(tfCurso.getText());
                    formEdit.setEscolaridade(String.valueOf(cbxEscolaridade.getSelectedItem()));
                    formEdit.setAnoInicio(tfAnoInicio.getText());
                    formEdit.setAnoFinal(tfAnoTermino.getText());
                    
                    formJPA.editar(formEdit);
                }
                
                dispose();
                
                PanelProfessor.preencherFormacao();
            }
        }
    }//GEN-LAST:event_brConfirmarActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btCancelarActionPerformed

    private void tfCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCursoActionPerformed

    private void tfInstituicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfInstituicaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfInstituicaoActionPerformed

    private void tfAnoTerminoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAnoTerminoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAnoTerminoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormFormacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormFormacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormFormacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormFormacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormFormacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brConfirmar;
    private javax.swing.JButton btCancelar;
    private javax.swing.JComboBox<String> cbxEscolaridade;
    private javax.swing.JLabel lbAnoInicio;
    private javax.swing.JLabel lbAnoTermino;
    private javax.swing.JLabel lbCurso;
    private javax.swing.JLabel lbEscolaridade;
    private javax.swing.JLabel lbFormacao;
    private javax.swing.JLabel lbInstituicao;
    private com.minha_sala_de_aula.Fabrica.PanelDegradeAzul panelDegradeAzul1;
    private com.minha_sala_de_aula.Fabrica.PanelFolhas panelFolhas1;
    private javax.swing.JPanel pnFormacao;
    private javax.swing.JTextField tfAnoInicio;
    private javax.swing.JTextField tfAnoTermino;
    private javax.swing.JTextField tfCurso;
    private javax.swing.JTextField tfInstituicao;
    // End of variables declaration//GEN-END:variables
    
    private boolean validarInstiuicao(){
        return tfInstituicao.getText().matches("[\\w\\W\\s]+");
    }
    
    private boolean validarCurso(){
        return tfCurso.getText().matches("[\\w\\W\\s]+");
    }
    
    private boolean validarInicio(){
        return tfAnoInicio.getText().matches("[1][9][0-9]{2}|[2][0][0-9]{2}");
    }
    
    private boolean validarTermino(){
        return tfAnoTermino.getText().matches("[1][9][0-9]{2}|[2][0][0-9]{2}");
    }
    
    @Override
    public boolean validarCampos(){
        return !validarInstiuicao() || !validarCurso() || !validarInicio() || !validarTermino();
    }
    
    @Override
    public boolean camposVazios(){
        return tfInstituicao.getText().isEmpty() || tfCurso.getText().isEmpty() || tfAnoInicio.getText().isEmpty() || tfAnoTermino.getText().isEmpty();
    }

    @Override
    public void mudarVermelho(JTextField tf) {
        tf.setBorder(BorderFactory.createLineBorder(new Color(175, 0 , 0)));
    }

    @Override
    public void mudarPadrao(JTextField tf) {
        tf.setBorder(BorderFactory.createLineBorder(new Color(255, 255, 153)));
    }

    @Override
    public void mudarCor() {        
        if (!validarInstiuicao()){
            mudarVermelho(tfInstituicao);
        }else{            
            mudarPadrao(tfInstituicao);
        }
        
        
        if (!validarCurso()){
            mudarVermelho(tfCurso);
        }else{            
            mudarPadrao(tfCurso);
        }
        
        
        if (!validarInicio()){
            mudarVermelho(tfAnoInicio);
        }else{            
            mudarPadrao(tfAnoInicio);
        }
        
        
        if (!validarTermino()){
            mudarVermelho(tfAnoTermino);
        }else{
            mudarPadrao(tfAnoTermino);
        } 
    }

}
