package com.minha_sala_de_aula.Fabrica;

public class PanelAulasHorarios extends javax.swing.JPanel {

    private boolean aulaFeita = false;
    
    public PanelDados getPanelDados(){
        return panelDados1;
    }
    
    public PanelAulasHorarios() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDados1 = new com.minha_sala_de_aula.Fabrica.PanelDados();
        lbHora = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lbTurma = new javax.swing.JLabel();
        lbNomeTurma = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        lbAula = new javax.swing.JLabel();
        lbNomeAula = new javax.swing.JLabel();
        btEdit = new javax.swing.JButton();
        btPlanejamento = new javax.swing.JButton();
        btMapaLink = new javax.swing.JButton();
        btFeita = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(802, 85));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        panelDados1.setPreferredSize(new java.awt.Dimension(802, 85));

        lbHora.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        lbHora.setForeground(new java.awt.Color(0, 0, 0));
        lbHora.setText("Hora");

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setToolTipText("");

        lbTurma.setFont(new java.awt.Font("Noto Sans", 0, 12)); // NOI18N
        lbTurma.setForeground(new java.awt.Color(0, 0, 0));
        lbTurma.setText("Turma");
        lbTurma.setToolTipText("");

        lbNomeTurma.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        lbNomeTurma.setForeground(new java.awt.Color(0, 0, 0));
        lbNomeTurma.setText("Nome da Turma");

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator2.setToolTipText("");

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setToolTipText("");

        lbAula.setFont(new java.awt.Font("Noto Sans", 0, 12)); // NOI18N
        lbAula.setForeground(new java.awt.Color(0, 0, 0));
        lbAula.setText("Aula");

        lbNomeAula.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        lbNomeAula.setForeground(new java.awt.Color(0, 0, 0));
        lbNomeAula.setText("Aula");

        btEdit.setIcon(new javax.swing.ImageIcon("/run/media/tomazaudio/ed644f64-c403-47df-b53b-4b1c2e37f556/SENAC/Projetos Java/Minha_Sala_de_Aula/src/resources/icon/Edit.png")); // NOI18N
        btEdit.setBorderPainted(false);
        btEdit.setContentAreaFilled(false);

        btPlanejamento.setIcon(new javax.swing.ImageIcon("/run/media/tomazaudio/ed644f64-c403-47df-b53b-4b1c2e37f556/SENAC/Projetos Java/Minha_Sala_de_Aula/src/resources/icon/Planejamento.png")); // NOI18N
        btPlanejamento.setBorderPainted(false);
        btPlanejamento.setContentAreaFilled(false);
        btPlanejamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPlanejamentoActionPerformed(evt);
            }
        });

        btMapaLink.setIcon(new javax.swing.ImageIcon("/run/media/tomazaudio/ed644f64-c403-47df-b53b-4b1c2e37f556/SENAC/Projetos Java/Minha_Sala_de_Aula/src/resources/icon/Map_pin.png")); // NOI18N
        btMapaLink.setBorderPainted(false);
        btMapaLink.setContentAreaFilled(false);

        btFeita.setIcon(new javax.swing.ImageIcon("/run/media/tomazaudio/ed644f64-c403-47df-b53b-4b1c2e37f556/SENAC/Projetos Java/Minha_Sala_de_Aula/src/resources/icon/Check-unchecked.png")); // NOI18N
        btFeita.setBorderPainted(false);
        btFeita.setContentAreaFilled(false);
        btFeita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btFeitaMouseClicked(evt);
            }
        });
        btFeita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFeitaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDados1Layout = new javax.swing.GroupLayout(panelDados1);
        panelDados1.setLayout(panelDados1Layout);
        panelDados1Layout.setHorizontalGroup(
            panelDados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDados1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(lbHora, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbTurma)
                    .addComponent(lbNomeTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(140, 140, 140)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbAula)
                    .addComponent(lbNomeAula))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 204, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btEdit)
                .addGap(0, 0, 0)
                .addComponent(btPlanejamento)
                .addGap(0, 0, 0)
                .addComponent(btMapaLink)
                .addGap(0, 0, 0)
                .addComponent(btFeita)
                .addGap(9, 9, 9))
        );
        panelDados1Layout.setVerticalGroup(
            panelDados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDados1Layout.createSequentialGroup()
                .addGroup(panelDados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDados1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelDados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDados1Layout.createSequentialGroup()
                                .addComponent(lbTurma)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbNomeTurma)
                                .addGap(0, 20, Short.MAX_VALUE))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelDados1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(panelDados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btMapaLink)
                                    .addComponent(btPlanejamento)
                                    .addComponent(btEdit))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelDados1Layout.createSequentialGroup()
                        .addGroup(panelDados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelDados1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(lbHora))
                            .addGroup(panelDados1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lbAula)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbNomeAula))
                            .addGroup(panelDados1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(btFeita)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelDados1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelDados1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btPlanejamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPlanejamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btPlanejamentoActionPerformed

    private void btFeitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFeitaActionPerformed
        if(!aulaFeita){
            aulaFeita = true;
            btFeita.setIcon(new javax.swing.ImageIcon("/run/media/tomazaudio/ed644f64-c403-47df-b53b-4b1c2e37f556/SENAC/Projetos Java/Minha_Sala_de_Aula/src/resources/icon/Check-checked.png"));
        }else{
            aulaFeita = false;
            btFeita.setIcon(new javax.swing.ImageIcon("/run/media/tomazaudio/ed644f64-c403-47df-b53b-4b1c2e37f556/SENAC/Projetos Java/Minha_Sala_de_Aula/src/resources/icon/Check-unchecked.png"));
        }
    }//GEN-LAST:event_btFeitaActionPerformed

    private void btFeitaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btFeitaMouseClicked
        
    }//GEN-LAST:event_btFeitaMouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEdit;
    private javax.swing.JButton btFeita;
    private javax.swing.JButton btMapaLink;
    private javax.swing.JButton btPlanejamento;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lbAula;
    private javax.swing.JLabel lbHora;
    private javax.swing.JLabel lbNomeAula;
    private javax.swing.JLabel lbNomeTurma;
    private javax.swing.JLabel lbTurma;
    private com.minha_sala_de_aula.Fabrica.PanelDados panelDados1;
    // End of variables declaration//GEN-END:variables
}
