/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.minha_sala_de_aula.Fabrica;

import javax.swing.JLabel;

/**
 *
 * @author tomazaudio
 */
public class PanelPacotes extends javax.swing.JPanel {

    public PanelDados getPanelDados1() {
        return panelDados1;
    }
    
    public JLabel getLbDuracaoPacote() {
        return lbDuracaoPacote;
    }

    public JLabel getLbNome() {
        return lbNome;
    }

    public JLabel getLbPerfil() {
        return lbPerfil;
    }

    public JLabel getLbRecorrencia() {
        return lbRecorrencia;
    }

    public JLabel getLbTipo() {
        return lbTipo;
    }

    public JLabel getLbValor() {
        return lbValor;
    }
    
    public PanelPacotes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDados1 = new com.minha_sala_de_aula.Fabrica.PanelDados();
        lbNome = new javax.swing.JLabel();
        lbTipo = new javax.swing.JLabel();
        lbBarra = new javax.swing.JLabel();
        lbPerfil = new javax.swing.JLabel();
        lbRecorrencia = new javax.swing.JLabel();
        lbDuracaoPacote = new javax.swing.JLabel();
        lbValor = new javax.swing.JLabel();

        lbNome.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        lbNome.setForeground(new java.awt.Color(0, 0, 0));
        lbNome.setText("Nome");

        lbTipo.setFont(new java.awt.Font("Noto Sans", 0, 12)); // NOI18N
        lbTipo.setForeground(new java.awt.Color(0, 0, 0));
        lbTipo.setText("Tipo");

        lbBarra.setFont(new java.awt.Font("Noto Sans", 0, 12)); // NOI18N
        lbBarra.setForeground(new java.awt.Color(0, 0, 0));
        lbBarra.setText("/");

        lbPerfil.setFont(new java.awt.Font("Noto Sans", 0, 12)); // NOI18N
        lbPerfil.setForeground(new java.awt.Color(0, 0, 0));
        lbPerfil.setText("Perfil");

        lbRecorrencia.setForeground(new java.awt.Color(0, 0, 0));
        lbRecorrencia.setText("Recorrencia");

        lbDuracaoPacote.setForeground(new java.awt.Color(0, 0, 0));
        lbDuracaoPacote.setText("Duração do Pacote");

        lbValor.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        lbValor.setForeground(new java.awt.Color(0, 0, 0));
        lbValor.setText("Valor");

        javax.swing.GroupLayout panelDados1Layout = new javax.swing.GroupLayout(panelDados1);
        panelDados1.setLayout(panelDados1Layout);
        panelDados1Layout.setHorizontalGroup(
            panelDados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDados1Layout.createSequentialGroup()
                .addComponent(lbNome)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panelDados1Layout.createSequentialGroup()
                .addGroup(panelDados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDados1Layout.createSequentialGroup()
                        .addComponent(lbTipo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbBarra, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbPerfil))
                    .addComponent(lbDuracaoPacote)
                    .addComponent(lbRecorrencia)
                    .addComponent(lbValor))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        panelDados1Layout.setVerticalGroup(
            panelDados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDados1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTipo)
                    .addComponent(lbBarra)
                    .addComponent(lbPerfil))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbRecorrencia)
                .addGap(12, 12, 12)
                .addComponent(lbDuracaoPacote)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbValor)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelDados1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelDados1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbBarra;
    private javax.swing.JLabel lbDuracaoPacote;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbPerfil;
    private javax.swing.JLabel lbRecorrencia;
    private javax.swing.JLabel lbTipo;
    private javax.swing.JLabel lbValor;
    private com.minha_sala_de_aula.Fabrica.PanelDados panelDados1;
    // End of variables declaration//GEN-END:variables
}
