package com.minha_sala_de_aula.Fabrica;

import javax.swing.JLabel;

public class PanelFormacao extends javax.swing.JPanel {

    public PanelDados getPanelDados1() {
        return panelDados1;
    }
    
    public JLabel getLbCurso() {
        return lbCurso;
    }

    public JLabel getLbInicio() {
        return lbInicio;
    }

    public JLabel getLbInstituicao() {
        return lbInstituicao;
    }

    public JLabel getLbNivel() {
        return lbNivel;
    }

    public JLabel getLbTermino() {
        return lbTermino;
    }
    
    public PanelFormacao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        panelDados1 = new com.minha_sala_de_aula.Fabrica.PanelDados();
        lbInstituicao = new javax.swing.JLabel();
        lbNivel = new javax.swing.JLabel();
        lbCurso = new javax.swing.JLabel();
        lbInicio = new javax.swing.JLabel();
        lbTermino = new javax.swing.JLabel();
        lbBarra = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        lbInstituicao.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        lbInstituicao.setForeground(new java.awt.Color(0, 0, 0));
        lbInstituicao.setText("Insituição");

        lbNivel.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        lbNivel.setForeground(new java.awt.Color(0, 0, 0));
        lbNivel.setText("Nível");

        lbCurso.setFont(new java.awt.Font("Noto Sans", 0, 16)); // NOI18N
        lbCurso.setForeground(new java.awt.Color(0, 0, 0));
        lbCurso.setText("Curso");

        lbInicio.setForeground(new java.awt.Color(0, 0, 0));
        lbInicio.setText("Inicio");

        lbTermino.setForeground(new java.awt.Color(0, 0, 0));
        lbTermino.setText("Termino");

        lbBarra.setForeground(new java.awt.Color(0, 0, 0));
        lbBarra.setText("/");

        javax.swing.GroupLayout panelDados1Layout = new javax.swing.GroupLayout(panelDados1);
        panelDados1.setLayout(panelDados1Layout);
        panelDados1Layout.setHorizontalGroup(
            panelDados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDados1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(panelDados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDados1Layout.createSequentialGroup()
                        .addComponent(lbCurso)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelDados1Layout.createSequentialGroup()
                        .addGroup(panelDados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelDados1Layout.createSequentialGroup()
                                .addComponent(lbInicio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbBarra)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbTermino))
                            .addComponent(lbNivel)
                            .addComponent(lbInstituicao))
                        .addContainerGap(150, Short.MAX_VALUE))))
        );
        panelDados1Layout.setVerticalGroup(
            panelDados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDados1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbNivel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbInstituicao)
                .addGap(18, 18, 18)
                .addComponent(lbCurso)
                .addGap(18, 18, 18)
                .addGroup(panelDados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTermino)
                    .addComponent(lbInicio)
                    .addComponent(lbBarra)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelDados1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelDados1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lbBarra;
    private javax.swing.JLabel lbCurso;
    private javax.swing.JLabel lbInicio;
    private javax.swing.JLabel lbInstituicao;
    private javax.swing.JLabel lbNivel;
    private javax.swing.JLabel lbTermino;
    private com.minha_sala_de_aula.Fabrica.PanelDados panelDados1;
    // End of variables declaration//GEN-END:variables
}
