package com.minha_sala_de_aula.Fabrica;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Component;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.event.MouseEvent;
import javax.swing.border.LineBorder;
import javax.swing.text.Style;

public class PanelDados extends javax.swing.JPanel {
    
    private boolean hover;
    private boolean selecionado;

    public boolean isSelecionado() {
        return selecionado;
    }

    public void setSelecionado(boolean selecionado) {
        this.selecionado = selecionado;
    }

    public boolean isHover() {
        return hover;
    }

    public void setHover(boolean hover) {
        this.hover = hover;
    }
    
    public PanelDados() {
        initComponents();
        this.setBorder(new LineBorder(new Color(0,0,0,0), 5, true));
        
        this.addMouseListener(new java.awt.event.MouseAdapter(){
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt){
                setHover(true);
                repaint();              
            }
            
            @Override
            public void mouseExited(java.awt.event.MouseEvent evt){
                setHover(false);
                repaint();                
            }
            
            public void mouseClicked(java.awt.event.MouseEvent evt){
                if(selecionado){
                    setSelecionado(false);
                    repaint(); 
                }else{
                    setSelecionado(true);
                    repaint();
                }
                                
            }

        });
        
    }
    
    @Override
    protected void paintComponent(Graphics g){
        Graphics2D g2 = (Graphics2D) g;
        if(isSelecionado()){ 
            g2.setColor(new Color(195, 191, 81)); //C3BF51
            g2.fillRoundRect(0, 0, getWidth(), getHeight(), 20, 20);
            g2.setColor(new Color(236, 230, 101)); //ECE665
            g2.fillRoundRect(0, 0, getWidth()-3, getHeight()-3, 20, 20);
            
        }else{
            if(isHover()){
                g2.setColor(Color.BLACK);
                g2.setStroke(new BasicStroke(2));
                g2.drawRoundRect(0, 0, getWidth(), getHeight(), 20, 20);
            }else{
                g2.setColor(new Color(0, 0, 0, 0));
                g2.drawRoundRect(0, 0, getWidth(), getHeight(), 20, 20);
            }
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        setOpaque(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 298, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        /*for (Component comp: getParent().getComponents()){
            PanelDados panel = (PanelDados) comp;
            panel.setSelecionado(false);
            panel.repaint();
        }*/
        
        /*if(evt.getButton() == MouseEvent.BUTTON1 && !selecionado){
            setSelecionado(true);
            repaint();
        }*/
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
