/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.minha_sala_de_aula.Calendario;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;

/**
 *
 * @author tomazaudio
 */
public class Calendario extends javax.swing.JPanel {
    
    private int mes;
    private int ano;
    /**
     * Creates new form Calendario
     */
    public Calendario() {
        initComponents();
        mesAtual();
        slide.show(new PanelCalDatas(mes, ano), SlidePanel.AnimateType.TO_RIGHT);
    }
    
    public void mesAtual(){
        Calendar calendario = Calendar.getInstance();
        calendario.setTime(new Date());
        mes = calendario.get(Calendar.MONTH);
        ano = calendario.get(Calendar.YEAR);
        SimpleDateFormat formato = new SimpleDateFormat("MMMM YYYY");
        lbMesAno.setText(formato.format(calendario.getTime()));
    }
    
    public void mostrarMesAno(){
        Calendar calendario = Calendar.getInstance();
        calendario.set(Calendar.MONTH, mes);
        calendario.set(Calendar.YEAR, ano);
        calendario.set(Calendar.DATE, 1);
        SimpleDateFormat formato = new SimpleDateFormat("MMMM YYYY");
        lbMesAno.setText(formato.format(calendario.getTime()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        slide = new com.minha_sala_de_aula.Calendario.SlidePanel();
        pnTopo = new javax.swing.JPanel();
        btAnterior = new javax.swing.JButton();
        lbMesAno = new javax.swing.JLabel();
        btProximo = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(343, 260));

        slide.setBackground(new java.awt.Color(255, 255, 255));

        pnTopo.setBackground(new java.awt.Color(255, 255, 255));

        btAnterior.setIcon(new javax.swing.ImageIcon("/run/media/tomazaudio/ed644f64-c403-47df-b53b-4b1c2e37f556/SENAC/Projetos Java/Minha_Sala_de_Aula/src/resources/icon/Calendario-mes-anterior.png")); // NOI18N
        btAnterior.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btAnterior.setContentAreaFilled(false);
        btAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAnteriorActionPerformed(evt);
            }
        });

        lbMesAno.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        lbMesAno.setForeground(new java.awt.Color(0, 0, 0));
        lbMesAno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbMesAno.setText("Mês Ano");

        btProximo.setIcon(new javax.swing.ImageIcon("/run/media/tomazaudio/ed644f64-c403-47df-b53b-4b1c2e37f556/SENAC/Projetos Java/Minha_Sala_de_Aula/src/resources/icon/Calendario-mes-proximo.png")); // NOI18N
        btProximo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btProximo.setContentAreaFilled(false);
        btProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProximoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnTopoLayout = new javax.swing.GroupLayout(pnTopo);
        pnTopo.setLayout(pnTopoLayout);
        pnTopoLayout.setHorizontalGroup(
            pnTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTopoLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btAnterior)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbMesAno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btProximo)
                .addGap(24, 24, 24))
        );
        pnTopoLayout.setVerticalGroup(
            pnTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTopoLayout.createSequentialGroup()
                .addGroup(pnTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnTopoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbMesAno, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnTopoLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(btAnterior))
                    .addGroup(pnTopoLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(btProximo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(slide, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
            .addComponent(pnTopo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnTopo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(slide, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAnteriorActionPerformed
        if(mes == 1){
            mes = 12;
            ano--;
        }else{
            mes--;
        }
        slide.show(new PanelCalDatas(mes, ano), SlidePanel.AnimateType.TO_RIGHT);
        mostrarMesAno();
    }//GEN-LAST:event_btAnteriorActionPerformed

    private void btProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProximoActionPerformed
        if(mes == 12){
            mes = 1;
            ano++;
        }else{
            mes++;
        }
        slide.show(new PanelCalDatas(mes, ano), SlidePanel.AnimateType.TO_RIGHT);
        mostrarMesAno();
    }//GEN-LAST:event_btProximoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAnterior;
    private javax.swing.JButton btProximo;
    private javax.swing.JLabel lbMesAno;
    private javax.swing.JPanel pnTopo;
    private com.minha_sala_de_aula.Calendario.SlidePanel slide;
    // End of variables declaration//GEN-END:variables
}
