package com.minha_sala_de_aula.Calendario;

import java.awt.Component;
import java.util.Calendar;
import java.util.Date;

public class PanelCalDatas extends javax.swing.JLayeredPane {
    
    private int mes;
    private int ano;
    
    /**
     * Creates new form PanelCalendario
     */
    public PanelCalDatas(int mes, int ano) {
        initComponents();
        this.mes = mes;
        this.ano = ano;
        setData();
    }
    
    
    private void setData(){
        Calendar calendar = Calendar.getInstance();
        calendar.set(Calendar.YEAR, ano);
        calendar.set(Calendar.MONTH, mes);  //  month jan as 0 so start from 0
        calendar.set(Calendar.DATE, 1);
        int diaInicial = calendar.get(Calendar.DAY_OF_WEEK) - 1;  //  get day of week -1 to index
        calendar.add(Calendar.DATE, -diaInicial);
        Hoje hoje = eHoje();
        for (int i = 7; i < getComponents().length; i++) {
            Celula celula = (Celula) getComponent(i);
            celula.setText(calendar.get(Calendar.DATE) + "");
            celula.setData(calendar.getTime());
            celula.mesAtual(calendar.get(Calendar.MONTH) == mes);
            if (hoje.eHoje(new Hoje(calendar.get(Calendar.DATE), calendar.get(Calendar.MONTH), calendar.get(Calendar.YEAR)))) {
                celula.setComoHoje();
            }            
            calendar.add(Calendar.DATE, 1);             
        }
    }
    
    private Hoje eHoje(){
        Calendar calendario = Calendar.getInstance();
        calendario.setTime(new Date());
        return new Hoje(calendario.get(Calendar.DATE), calendario.get(Calendar.MONTH), calendario.get(Calendar.YEAR));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbDom = new javax.swing.JLabel();
        lbSeg = new javax.swing.JLabel();
        lbTer = new javax.swing.JLabel();
        lbQua = new javax.swing.JLabel();
        lbQui = new javax.swing.JLabel();
        lbSex = new javax.swing.JLabel();
        lbSab = new javax.swing.JLabel();
        celula1 = new com.minha_sala_de_aula.Calendario.Celula();
        celula2 = new com.minha_sala_de_aula.Calendario.Celula();
        celula3 = new com.minha_sala_de_aula.Calendario.Celula();
        celula4 = new com.minha_sala_de_aula.Calendario.Celula();
        celula5 = new com.minha_sala_de_aula.Calendario.Celula();
        celula6 = new com.minha_sala_de_aula.Calendario.Celula();
        celula7 = new com.minha_sala_de_aula.Calendario.Celula();
        celula8 = new com.minha_sala_de_aula.Calendario.Celula();
        celula9 = new com.minha_sala_de_aula.Calendario.Celula();
        celula10 = new com.minha_sala_de_aula.Calendario.Celula();
        celula11 = new com.minha_sala_de_aula.Calendario.Celula();
        celula12 = new com.minha_sala_de_aula.Calendario.Celula();
        celula13 = new com.minha_sala_de_aula.Calendario.Celula();
        celula14 = new com.minha_sala_de_aula.Calendario.Celula();
        celula15 = new com.minha_sala_de_aula.Calendario.Celula();
        celula16 = new com.minha_sala_de_aula.Calendario.Celula();
        celula17 = new com.minha_sala_de_aula.Calendario.Celula();
        celula18 = new com.minha_sala_de_aula.Calendario.Celula();
        celula19 = new com.minha_sala_de_aula.Calendario.Celula();
        celula20 = new com.minha_sala_de_aula.Calendario.Celula();
        celula21 = new com.minha_sala_de_aula.Calendario.Celula();
        celula22 = new com.minha_sala_de_aula.Calendario.Celula();
        celula23 = new com.minha_sala_de_aula.Calendario.Celula();
        celula24 = new com.minha_sala_de_aula.Calendario.Celula();
        celula25 = new com.minha_sala_de_aula.Calendario.Celula();
        celula26 = new com.minha_sala_de_aula.Calendario.Celula();
        celula27 = new com.minha_sala_de_aula.Calendario.Celula();
        celula28 = new com.minha_sala_de_aula.Calendario.Celula();
        celula29 = new com.minha_sala_de_aula.Calendario.Celula();
        celula30 = new com.minha_sala_de_aula.Calendario.Celula();
        celula31 = new com.minha_sala_de_aula.Calendario.Celula();
        celula32 = new com.minha_sala_de_aula.Calendario.Celula();
        celula33 = new com.minha_sala_de_aula.Calendario.Celula();
        celula34 = new com.minha_sala_de_aula.Calendario.Celula();
        celula35 = new com.minha_sala_de_aula.Calendario.Celula();
        celula36 = new com.minha_sala_de_aula.Calendario.Celula();
        celula37 = new com.minha_sala_de_aula.Calendario.Celula();
        celula38 = new com.minha_sala_de_aula.Calendario.Celula();
        celula39 = new com.minha_sala_de_aula.Calendario.Celula();
        celula40 = new com.minha_sala_de_aula.Calendario.Celula();
        celula41 = new com.minha_sala_de_aula.Calendario.Celula();
        celula42 = new com.minha_sala_de_aula.Calendario.Celula();

        setLayout(new java.awt.GridLayout(7, 7));

        lbDom.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        lbDom.setForeground(new java.awt.Color(255, 51, 51));
        lbDom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbDom.setText("D");
        add(lbDom);

        lbSeg.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        lbSeg.setForeground(new java.awt.Color(0, 0, 0));
        lbSeg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbSeg.setText("S");
        add(lbSeg);

        lbTer.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        lbTer.setForeground(new java.awt.Color(0, 0, 0));
        lbTer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTer.setText("T");
        add(lbTer);

        lbQua.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        lbQua.setForeground(new java.awt.Color(0, 0, 0));
        lbQua.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbQua.setText("Q");
        add(lbQua);

        lbQui.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        lbQui.setForeground(new java.awt.Color(0, 0, 0));
        lbQui.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbQui.setText("Q");
        add(lbQui);

        lbSex.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        lbSex.setForeground(new java.awt.Color(0, 0, 0));
        lbSex.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbSex.setText("S");
        add(lbSex);

        lbSab.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        lbSab.setForeground(new java.awt.Color(0, 0, 0));
        lbSab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbSab.setText("S");
        add(lbSab);
        add(celula1);
        add(celula2);
        add(celula3);
        add(celula4);
        add(celula5);
        add(celula6);
        add(celula7);
        add(celula8);
        add(celula9);
        add(celula10);
        add(celula11);
        add(celula12);
        add(celula13);
        add(celula14);
        add(celula15);
        add(celula16);
        add(celula17);
        add(celula18);
        add(celula19);
        add(celula20);
        add(celula21);
        add(celula22);
        add(celula23);
        add(celula24);
        add(celula25);
        add(celula26);
        add(celula27);
        add(celula28);
        add(celula29);
        add(celula30);
        add(celula31);
        add(celula32);
        add(celula33);
        add(celula34);
        add(celula35);
        add(celula36);
        add(celula37);
        add(celula38);
        add(celula39);
        add(celula40);
        add(celula41);
        add(celula42);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.minha_sala_de_aula.Calendario.Celula celula1;
    private com.minha_sala_de_aula.Calendario.Celula celula10;
    private com.minha_sala_de_aula.Calendario.Celula celula11;
    private com.minha_sala_de_aula.Calendario.Celula celula12;
    private com.minha_sala_de_aula.Calendario.Celula celula13;
    private com.minha_sala_de_aula.Calendario.Celula celula14;
    private com.minha_sala_de_aula.Calendario.Celula celula15;
    private com.minha_sala_de_aula.Calendario.Celula celula16;
    private com.minha_sala_de_aula.Calendario.Celula celula17;
    private com.minha_sala_de_aula.Calendario.Celula celula18;
    private com.minha_sala_de_aula.Calendario.Celula celula19;
    private com.minha_sala_de_aula.Calendario.Celula celula2;
    private com.minha_sala_de_aula.Calendario.Celula celula20;
    private com.minha_sala_de_aula.Calendario.Celula celula21;
    private com.minha_sala_de_aula.Calendario.Celula celula22;
    private com.minha_sala_de_aula.Calendario.Celula celula23;
    private com.minha_sala_de_aula.Calendario.Celula celula24;
    private com.minha_sala_de_aula.Calendario.Celula celula25;
    private com.minha_sala_de_aula.Calendario.Celula celula26;
    private com.minha_sala_de_aula.Calendario.Celula celula27;
    private com.minha_sala_de_aula.Calendario.Celula celula28;
    private com.minha_sala_de_aula.Calendario.Celula celula29;
    private com.minha_sala_de_aula.Calendario.Celula celula3;
    private com.minha_sala_de_aula.Calendario.Celula celula30;
    private com.minha_sala_de_aula.Calendario.Celula celula31;
    private com.minha_sala_de_aula.Calendario.Celula celula32;
    private com.minha_sala_de_aula.Calendario.Celula celula33;
    private com.minha_sala_de_aula.Calendario.Celula celula34;
    private com.minha_sala_de_aula.Calendario.Celula celula35;
    private com.minha_sala_de_aula.Calendario.Celula celula36;
    private com.minha_sala_de_aula.Calendario.Celula celula37;
    private com.minha_sala_de_aula.Calendario.Celula celula38;
    private com.minha_sala_de_aula.Calendario.Celula celula39;
    private com.minha_sala_de_aula.Calendario.Celula celula4;
    private com.minha_sala_de_aula.Calendario.Celula celula40;
    private com.minha_sala_de_aula.Calendario.Celula celula41;
    private com.minha_sala_de_aula.Calendario.Celula celula42;
    private com.minha_sala_de_aula.Calendario.Celula celula5;
    private com.minha_sala_de_aula.Calendario.Celula celula6;
    private com.minha_sala_de_aula.Calendario.Celula celula7;
    private com.minha_sala_de_aula.Calendario.Celula celula8;
    private com.minha_sala_de_aula.Calendario.Celula celula9;
    private javax.swing.JLabel lbDom;
    private javax.swing.JLabel lbQua;
    private javax.swing.JLabel lbQui;
    private javax.swing.JLabel lbSab;
    private javax.swing.JLabel lbSeg;
    private javax.swing.JLabel lbSex;
    private javax.swing.JLabel lbTer;
    // End of variables declaration//GEN-END:variables
}
