package com.minha_sala_de_aula.GUI;

import com.minha_sala_de_aula.Professor.*;
import java.awt.Container;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class GUI_Principal extends javax.swing.JFrame {

    private static Professor professor;
    
    public static Professor getProfessor(){
        return professor;
    }
    
    public static Professor ProfessorInicial(){
        return professor = new Professor();
    }
    
    public static void atualizarProf(){
        ProfessorJPA profJpa = new ProfessorJPA();
        professor = profJpa.consultaProf();
    }
    
    public GUI_Principal() {    
        ProfessorJPA profJpa = new ProfessorJPA();
        professor = profJpa.consultaProf();
        
        initComponents();
        PanelProfessor.infoProf();
        PanelProfessor.preencherFormacao();
        PanelProfessor.preencherPacotes();
    }
    
    public static void verificarProfessor(){
        if(professor == null){
            FormProfessor form = new FormProfessor();
            form.getBtCancelar().setEnabled(false);
            form.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
            form.setVisible(true);
            JOptionPane.showMessageDialog(null, """
                        Bem vindo(a/e) ao Minha Sala de Aula!!! 

         Para começar a usar seu gerenciador de aulas particulares é necessário
         cadastrar suas informações como profissional. Preencha o cadastro inicial
         e você seguirá para a tela principal de suas aulas. Bom proveito e que
         tenha bastante alunos(as/es).
                                                    """);
            
            form.requestFocus();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDegrade = new com.minha_sala_de_aula.Fabrica.PanelDegradeAzul();
        tbpnArquivo = new javax.swing.JTabbedPane();
        pnCalendario = new com.minha_sala_de_aula.GUI.PanelCalendario();
        panelProfessor = new com.minha_sala_de_aula.GUI.PanelProfessor();
        panelTurmas = new com.minha_sala_de_aula.GUI.PanelTurmas();
        panelMenu1 = new com.minha_sala_de_aula.Fabrica.PanelMenu();
        btSalvar = new javax.swing.JButton();
        btConfiguracoes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 1366, 768));
        setResizable(false);

        panelDegrade.setPreferredSize(new java.awt.Dimension(1366, 768));

        tbpnArquivo.setForeground(new java.awt.Color(0, 0, 0));

        pnCalendario.setBackground(new java.awt.Color(255, 255, 153));
        tbpnArquivo.addTab("Calendario", pnCalendario);
        tbpnArquivo.addTab("Professor", panelProfessor);
        tbpnArquivo.addTab("Turmas", panelTurmas);

        btSalvar.setIcon(new javax.swing.ImageIcon("/run/media/tomazaudio/ed644f64-c403-47df-b53b-4b1c2e37f556/SENAC/Projetos Java/Minha_Sala_de_Aula/src/main/resources/icon/Save.png")); // NOI18N
        btSalvar.setBorderPainted(false);
        btSalvar.setContentAreaFilled(false);
        btSalvar.setRolloverEnabled(false);

        btConfiguracoes.setIcon(new javax.swing.ImageIcon("/run/media/tomazaudio/ed644f64-c403-47df-b53b-4b1c2e37f556/SENAC/Projetos Java/Minha_Sala_de_Aula/src/main/resources/icon/Settings.png")); // NOI18N
        btConfiguracoes.setBorderPainted(false);
        btConfiguracoes.setContentAreaFilled(false);
        btConfiguracoes.setRolloverEnabled(false);
        btConfiguracoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConfiguracoesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMenu1Layout = new javax.swing.GroupLayout(panelMenu1);
        panelMenu1.setLayout(panelMenu1Layout);
        panelMenu1Layout.setHorizontalGroup(
            panelMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenu1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(btSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btConfiguracoes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelMenu1Layout.setVerticalGroup(
            panelMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenu1Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(panelMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btConfiguracoes)
                    .addComponent(btSalvar))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout panelDegradeLayout = new javax.swing.GroupLayout(panelDegrade);
        panelDegrade.setLayout(panelDegradeLayout);
        panelDegradeLayout.setHorizontalGroup(
            panelDegradeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDegradeLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(tbpnArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 1285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
            .addComponent(panelMenu1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelDegradeLayout.setVerticalGroup(
            panelDegradeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDegradeLayout.createSequentialGroup()
                .addComponent(panelMenu1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tbpnArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelDegrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelDegrade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btConfiguracoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConfiguracoesActionPerformed
        GuiConfiguracoes configuracoes = new GuiConfiguracoes();
        configuracoes.setVisible(true);
    }//GEN-LAST:event_btConfiguracoesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new GUI_Principal().setVisible(true);
                verificarProfessor();
                PanelProfessor.preencherFormacao();
                PanelProfessor.preencherPacotes();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btConfiguracoes;
    private javax.swing.JButton btSalvar;
    private com.minha_sala_de_aula.Fabrica.PanelDegradeAzul panelDegrade;
    private com.minha_sala_de_aula.Fabrica.PanelMenu panelMenu1;
    private com.minha_sala_de_aula.GUI.PanelProfessor panelProfessor;
    private com.minha_sala_de_aula.GUI.PanelTurmas panelTurmas;
    private com.minha_sala_de_aula.GUI.PanelCalendario pnCalendario;
    private javax.swing.JTabbedPane tbpnArquivo;
    // End of variables declaration//GEN-END:variables
}
