/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.minha_sala_de_aula.GUI;

import com.minha_sala_de_aula.Turmas.GuiAlunos;

/**
 *
 * @author tomazaudio
 */
public class PanelTurmas extends javax.swing.JPanel {

    /**
     * Creates new form PanelTurmas
     */
    public PanelTurmas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        separador = new javax.swing.JSeparator();
        scrlpnTurmas = new javax.swing.JScrollPane();
        laypnTurmas = new javax.swing.JLayeredPane();
        pnDadosTurma = new javax.swing.JPanel();
        scrlpnAulas = new javax.swing.JScrollPane();
        laypnAulas = new javax.swing.JLayeredPane();
        scrlpnPagamentos = new javax.swing.JScrollPane();
        laypnPagamentos = new javax.swing.JLayeredPane();
        lbObservavao = new javax.swing.JLabel();
        scrlpnObservacao = new javax.swing.JScrollPane();
        tpObservacao = new javax.swing.JTextPane();
        lbTipo = new javax.swing.JLabel();
        lbPerfil = new javax.swing.JLabel();
        lbValor = new javax.swing.JLabel();
        lbData = new javax.swing.JLabel();
        lbTipoRetorno = new javax.swing.JLabel();
        lbPerfilRetorno = new javax.swing.JLabel();
        lbValorRetorno = new javax.swing.JLabel();
        lbDataRetorno = new javax.swing.JLabel();
        lbAlunos = new javax.swing.JLabel();
        lbListaAlunos = new javax.swing.JLabel();
        lbAulas = new javax.swing.JLabel();
        lbPagamentos = new javax.swing.JLabel();
        btEditaAluno = new javax.swing.JButton();
        btListagem = new javax.swing.JButton();
        btAddAlunos = new javax.swing.JButton();
        btExcluiAlunos = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        lbDadosTurma = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setBackground(new java.awt.Color(255, 255, 153));
        setPreferredSize(new java.awt.Dimension(1285, 571));

        separador.setOrientation(javax.swing.SwingConstants.VERTICAL);

        scrlpnTurmas.setBackground(new java.awt.Color(255, 255, 153));
        scrlpnTurmas.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        laypnTurmas.setLayout(new java.awt.GridLayout(40, 1));
        scrlpnTurmas.setViewportView(laypnTurmas);

        pnDadosTurma.setBackground(new java.awt.Color(255, 255, 255));

        scrlpnAulas.setBackground(new java.awt.Color(239, 235, 194));
        scrlpnAulas.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        laypnAulas.setLayout(new java.awt.GridLayout(40, 1));
        scrlpnAulas.setViewportView(laypnAulas);

        scrlpnPagamentos.setBackground(new java.awt.Color(239, 235, 194));
        scrlpnPagamentos.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        laypnPagamentos.setLayout(new java.awt.GridLayout(40, 1));
        scrlpnPagamentos.setViewportView(laypnPagamentos);

        lbObservavao.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        lbObservavao.setForeground(new java.awt.Color(0, 0, 0));
        lbObservavao.setText("Observação:");

        scrlpnObservacao.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        tpObservacao.setBackground(new java.awt.Color(255, 255, 255));
        tpObservacao.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tpObservacao.setEnabled(false);
        scrlpnObservacao.setViewportView(tpObservacao);

        lbTipo.setForeground(new java.awt.Color(0, 0, 0));
        lbTipo.setText("Tipo:");

        lbPerfil.setForeground(new java.awt.Color(0, 0, 0));
        lbPerfil.setText("Perfil:");

        lbValor.setForeground(new java.awt.Color(0, 0, 0));
        lbValor.setText("Valor Acertado:");

        lbData.setForeground(new java.awt.Color(0, 0, 0));
        lbData.setText("Data de Pagamento:");

        lbTipoRetorno.setForeground(new java.awt.Color(0, 0, 0));

        lbPerfilRetorno.setForeground(new java.awt.Color(0, 0, 0));

        lbValorRetorno.setForeground(new java.awt.Color(0, 0, 0));

        lbDataRetorno.setForeground(new java.awt.Color(0, 0, 0));

        lbAlunos.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        lbAlunos.setForeground(new java.awt.Color(0, 0, 0));
        lbAlunos.setText("Alunos(as/es)");

        lbListaAlunos.setForeground(new java.awt.Color(0, 0, 0));

        lbAulas.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        lbAulas.setForeground(new java.awt.Color(0, 0, 0));
        lbAulas.setText("Aulas");

        lbPagamentos.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        lbPagamentos.setForeground(new java.awt.Color(0, 0, 0));
        lbPagamentos.setText("Pag.");

        btEditaAluno.setIcon(new javax.swing.ImageIcon("/run/media/tomazaudio/ed644f64-c403-47df-b53b-4b1c2e37f556/SENAC/Projetos Java/Minha_Sala_de_Aula/src/resources/icon/Edit-menor.png")); // NOI18N
        btEditaAluno.setBorderPainted(false);
        btEditaAluno.setContentAreaFilled(false);
        btEditaAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditaAlunoActionPerformed(evt);
            }
        });

        btListagem.setIcon(new javax.swing.ImageIcon("/run/media/tomazaudio/ed644f64-c403-47df-b53b-4b1c2e37f556/SENAC/Projetos Java/Minha_Sala_de_Aula/src/resources/icon/Aluno_verAlunos.png")); // NOI18N
        btListagem.setBorderPainted(false);
        btListagem.setContentAreaFilled(false);
        btListagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btListagemActionPerformed(evt);
            }
        });

        btAddAlunos.setIcon(new javax.swing.ImageIcon("/run/media/tomazaudio/ed644f64-c403-47df-b53b-4b1c2e37f556/SENAC/Projetos Java/Minha_Sala_de_Aula/src/resources/icon/Aluno_adicionar.png")); // NOI18N
        btAddAlunos.setBorderPainted(false);
        btAddAlunos.setContentAreaFilled(false);

        btExcluiAlunos.setIcon(new javax.swing.ImageIcon("/run/media/tomazaudio/ed644f64-c403-47df-b53b-4b1c2e37f556/SENAC/Projetos Java/Minha_Sala_de_Aula/src/resources/icon/Aluno_deletar.png")); // NOI18N
        btExcluiAlunos.setBorderPainted(false);
        btExcluiAlunos.setContentAreaFilled(false);

        jButton1.setIcon(new javax.swing.ImageIcon("/run/media/tomazaudio/ed644f64-c403-47df-b53b-4b1c2e37f556/SENAC/Projetos Java/Minha_Sala_de_Aula/src/resources/icon/Add_Aula.png")); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon("/run/media/tomazaudio/ed644f64-c403-47df-b53b-4b1c2e37f556/SENAC/Projetos Java/Minha_Sala_de_Aula/src/resources/icon/Exibir_Aula.png")); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);

        jButton3.setIcon(new javax.swing.ImageIcon("/run/media/tomazaudio/ed644f64-c403-47df-b53b-4b1c2e37f556/SENAC/Projetos Java/Minha_Sala_de_Aula/src/resources/icon/Seta_baixo.png")); // NOI18N
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);

        jButton5.setIcon(new javax.swing.ImageIcon("/run/media/tomazaudio/ed644f64-c403-47df-b53b-4b1c2e37f556/SENAC/Projetos Java/Minha_Sala_de_Aula/src/resources/icon/Add_Pagamento.png")); // NOI18N
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);

        jButton4.setIcon(new javax.swing.ImageIcon("/run/media/tomazaudio/ed644f64-c403-47df-b53b-4b1c2e37f556/SENAC/Projetos Java/Minha_Sala_de_Aula/src/resources/icon/Trash-menor.png")); // NOI18N
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);

        javax.swing.GroupLayout pnDadosTurmaLayout = new javax.swing.GroupLayout(pnDadosTurma);
        pnDadosTurma.setLayout(pnDadosTurmaLayout);
        pnDadosTurmaLayout.setHorizontalGroup(
            pnDadosTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDadosTurmaLayout.createSequentialGroup()
                .addGroup(pnDadosTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnDadosTurmaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(pnDadosTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnDadosTurmaLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(pnDadosTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnDadosTurmaLayout.createSequentialGroup()
                                        .addComponent(lbObservavao)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(scrlpnObservacao, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lbAlunos)))
                            .addGroup(pnDadosTurmaLayout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addGroup(pnDadosTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbValor)
                                    .addComponent(lbTipo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnDadosTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbValorRetorno, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                                    .addComponent(lbTipoRetorno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnDadosTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbPerfil, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbData, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnDadosTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbPerfilRetorno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbDataRetorno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(pnDadosTurmaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnDadosTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbListaAlunos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pnDadosTurmaLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(pnDadosTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(pnDadosTurmaLayout.createSequentialGroup()
                                        .addComponent(btEditaAluno)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btListagem)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btAddAlunos)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btExcluiAlunos))
                                    .addGroup(pnDadosTurmaLayout.createSequentialGroup()
                                        .addComponent(scrlpnAulas, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(scrlpnPagamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnDadosTurmaLayout.createSequentialGroup()
                                        .addComponent(lbAulas)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton3)
                                        .addGap(139, 139, 139)
                                        .addComponent(lbPagamentos)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton4)
                                        .addGap(8, 8, 8)))))
                        .addGap(9, 9, 9)))
                .addContainerGap())
        );
        pnDadosTurmaLayout.setVerticalGroup(
            pnDadosTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnDadosTurmaLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pnDadosTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbObservavao)
                    .addComponent(scrlpnObservacao, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(pnDadosTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnDadosTurmaLayout.createSequentialGroup()
                        .addComponent(lbPerfilRetorno, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbDataRetorno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnDadosTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnDadosTurmaLayout.createSequentialGroup()
                            .addComponent(lbPerfil)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lbData))
                        .addGroup(pnDadosTurmaLayout.createSequentialGroup()
                            .addGroup(pnDadosTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lbTipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbTipoRetorno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(pnDadosTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbValor)
                                .addComponent(lbValorRetorno, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(pnDadosTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnDadosTurmaLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lbAlunos))
                    .addGroup(pnDadosTurmaLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(pnDadosTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btAddAlunos, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btListagem, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btExcluiAlunos)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnDadosTurmaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btEditaAluno)))
                .addGap(6, 6, 6)
                .addComponent(lbListaAlunos, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnDadosTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnDadosTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbPagamentos)
                        .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(pnDadosTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbAulas)
                            .addComponent(jButton1)
                            .addComponent(jButton2)))
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnDadosTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(scrlpnPagamentos)
                    .addComponent(scrlpnAulas, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );

        lbDadosTurma.setFont(new java.awt.Font("Noto Sans", 1, 36)); // NOI18N
        lbDadosTurma.setForeground(new java.awt.Color(0, 0, 0));
        lbDadosTurma.setText("Dados da Turma");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrlpnTurmas, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(separador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(lbDadosTurma))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(pnDadosTurma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(separador)
                        .addComponent(scrlpnTurmas, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbDadosTurma)
                        .addGap(18, 18, 18)
                        .addComponent(pnDadosTurma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btEditaAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditaAlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btEditaAlunoActionPerformed

    private void btListagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btListagemActionPerformed
        GuiAlunos listaAlunos = new GuiAlunos();
        listaAlunos.setVisible(true);
    }//GEN-LAST:event_btListagemActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAddAlunos;
    private javax.swing.JButton btEditaAluno;
    private javax.swing.JButton btExcluiAlunos;
    private javax.swing.JButton btListagem;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane laypnAulas;
    private javax.swing.JLayeredPane laypnPagamentos;
    private javax.swing.JLayeredPane laypnTurmas;
    private javax.swing.JLabel lbAlunos;
    private javax.swing.JLabel lbAulas;
    private javax.swing.JLabel lbDadosTurma;
    private javax.swing.JLabel lbData;
    private javax.swing.JLabel lbDataRetorno;
    private javax.swing.JLabel lbListaAlunos;
    private javax.swing.JLabel lbObservavao;
    private javax.swing.JLabel lbPagamentos;
    private javax.swing.JLabel lbPerfil;
    private javax.swing.JLabel lbPerfilRetorno;
    private javax.swing.JLabel lbTipo;
    private javax.swing.JLabel lbTipoRetorno;
    private javax.swing.JLabel lbValor;
    private javax.swing.JLabel lbValorRetorno;
    private javax.swing.JPanel pnDadosTurma;
    private javax.swing.JScrollPane scrlpnAulas;
    private javax.swing.JScrollPane scrlpnObservacao;
    private javax.swing.JScrollPane scrlpnPagamentos;
    private javax.swing.JScrollPane scrlpnTurmas;
    private javax.swing.JSeparator separador;
    private javax.swing.JTextPane tpObservacao;
    // End of variables declaration//GEN-END:variables
}
